backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /app/

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /app/
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /app/