security:
  firewalls:
    backend:
      pattern: ^/app
      provider: usuarios
      anonymous: ~
      form_login:
        login_path: admin_login
        check_path: admin_login_check
      remember_me:
        key: siakey
        lifetime: 3600
      logout:
        path: /app/logout
        target: /app
  access_control:
    - { path: ^/app/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/app/*, roles: ROLE_ADMIN }
  providers:
    usuarios:
      entity: { class: Cdti\BackendBundle\Entity\Usuario, property: usuario }
  encoders:
    Cdti\BackendBundle\Entity\Usuario: { algorithm: sha512 }