backend_producto:
    pattern:  /
    defaults: { _controller: "BackendBundle:Producto:index" }

backend_producto_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Producto:show" }

backend_producto_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Producto:new" }

backend_producto_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Producto:create" }
    requirements: { _method: post }

backend_producto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Producto:edit" }

backend_producto_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Producto:update" }
    requirements: { _method: post }

backend_producto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendBundle:Producto:delete" }
    requirements: { _method: post }
